from turtle import *
from random import randint

def h(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(100)
    turtle.back(45)
    turtle.right(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(55)
    turtle.back(100)
def a(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y)
    turtle.pendown()
    turtle.back(100)
    turtle.left(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(100)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(70)
def p(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y)
    turtle.pendown()
    turtle.left(90)
    turtle.back(100)
    turtle.left(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(70)
def y(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y) 
    turtle.left(90)
    turtle.back(50)
    turtle.pendown()
    turtle.back(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(70)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(70)
    turtle.back(35)
    turtle.left(90)
    turtle.forward(60)
def n(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y) 
    turtle.pendown()
    turtle.back(90)
    turtle.left(35)
    turtle.forward(109)
    turtle.left(145)
    turtle.forward(90)
def e(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y) 
    turtle.pendown()
    turtle.back(93)
    turtle.right(90)
    turtle.forward(60)
    turtle.back(62)
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(32)
    turtle.back(32)
    turtle.left(90)
    turtle.forward(47)
    turtle.right(90)
    turtle.forward(60)
def e2(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y) 
    turtle.pendown()
    turtle.right(180)
    turtle.back(93)
    turtle.right(90)
    turtle.forward(60)
    turtle.back(62)
    turtle.left(90)
    turtle.forward(45)
    turtle.right(90)
    turtle.forward(32)
    turtle.back(32)
    turtle.left(90)
    turtle.forward(47)
    turtle.right(90)
    turtle.forward(60)
def w(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y) 
    turtle.pendown()
    turtle.right(90)
    turtle.forward(93)
    turtle.left(130)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(45)
    turtle.left(140)
    turtle.forward(95)
    turtle.back(90)
    turtle.left(90)
def a2(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y)
    turtle.pendown()
    turtle.right(90)
    turtle.back(100)
    turtle.left(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(100)
    turtle.back(50)
    turtle.right(90)
    turtle.forward(70)
def r(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y)
    turtle.pendown()
    turtle.left(90)
    turtle.back(100)
    turtle.left(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(60)
    turtle.left(140)
    turtle.forward(75)
    turtle.left(140)
    turtle.penup()
def two(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.penup()
    turtle.home()
def zero(turtle, color, x, y, width, height):
    turtle.penup()
    turtle.color(color)
    turtle.goto(x, y)
    turtle.pendown()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(100)
    
    turtle.penup()
    turtle.home()


BG_COLOR = "#0080ff"

myturtle = Turtle()
# set turtle speed
myturtle.speed(9)
myturtle.pensize(20)

screen = myturtle.getscreen()
# set background color
screen.bgcolor(BG_COLOR)
# set tile of screen
screen.title("Happy New Year")
# maximize the screen
screen.setup(width=1.0, height=1.0)


# create tree trunk
h(myturtle, "aqua", -400, 300, 30, 60)
a(myturtle, "red", -280, 300, 30, 60)
p(myturtle, "green", -160, 300, 30, 60)
p(myturtle, "brown", -45, 300, 30, 60)
y(myturtle, "white", 70, 300, 30, 60)
n(myturtle, "white", -280,100, 30, 60)
e(myturtle, "gray", -170,190, 30, 60)
w(myturtle, "aqua", -63,190, 30, 60)
y(myturtle, "white", -360, -90, 30, 60)
e2(myturtle, "gray", -240,10, 30, 60)
a2(myturtle, "red", -140, -90, 30, 60)
r(myturtle, "red", -10, -90, 30, 60)
myturtle.home()
two(myturtle, "gold", -370, -190, 30, 60)
zero(myturtle, "gold", -250, -190, 30, 60)
two(myturtle, "gold", -130, -190, 30, 60)
zero(myturtle, "gold", -15, -190, 30, 60)
# create_rectangle(myturtle, "red", -15, y-60, 30, 60)
# create a star a top of tree
# now add few stars in sky
myturtle.speed(10)
number_of_stars = randint(0,10)
# print(number_of_stars)
for _ in range(0,number_of_stars):
    x_star = randint(-(screen.window_width()//2),screen.window_width()//2)
    y_star = randint(60, screen.window_height()//2)
    size = randint(5,20)
    myturtle.pensize(2)
    myturtle.penup()
    myturtle.color('gold')
    myturtle.goto(x_star, y_star)
    myturtle.begin_fill()
    myturtle.pendown()
    for i in range(5):
        myturtle.forward(size)
        myturtle.right(144)
    myturtle.end_fill()

screen.mainloop()
